# Generated by Django 4.1.3 on 2023-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunjungan',
            name='id_kepuasan',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
